...->*+Machine: new Machine()
Machine->*FuelTank: new FuelTank()
Machine->FuelTank: fill(40)
Machine->*Engine: new Engine(tank)
Machine-->-...: &Machine
...->+Machine: drive()
Machine->+Engine: start()
Engine->FuelTank: consume(5)
Engine-->-Machine:
Machine->+Engine: isRunning()
Engine->+FuelTank: contentsLeft()
FuelTank-->-Engine: 35
Engine-->-Machine: true
Machine->+Engine: useEnergy()
Engine->FuelTank: consume(10)
Engine-->-Machine:
Machine-->-...:
